### ISSUE TITLE
[Wiki PR] Mention `dvrk_arm_test.py` in examples

### ISSUE THREAD

**Issue by RobertoRoos** [jhu-dvrk/sawIntuitiveResearchKit#137]
Let's give this a try as sort of a wiki pull request.

I would suggest we mention the script `dvrk_arm_test.py` explicitly on the wiki, since this script was exactly what I was looking for when I was done calibrating. It also works very well as an initial hardware validation step.

See **https://github.com/RobertoRoos/sawIntuitiveResearchKitWiki/pull/1**

I've also made a little graphic showing the ECM brake current.

See **See **https://github.com/RobertoRoos/sawIntuitiveResearchKitWiki/pull/2**

@adeguet1 what do you think?

_I have forked the wiki-repo into a regular repo in my workspace. The master branch is kept identical to the official wiki and I've made contributions in local branches there. By creating a pull request there we can have a clean online overview of the changes._

**Comment by RobertoRoos** [comment]
I've also added a little calibration table in the same branch:

![image](https://user-images.githubusercontent.com/12717020/125407652-62721d00-e3ba-11eb-97b0-a88a4770ef85.png)

**Comment by adeguet1** [comment]
Is your "fork" private?   The link to https://github.com/RobertoRoos/sawIntuitiveResearchKit.wiki.git leads to a 404 page on my end.

**Comment by RobertoRoos** [comment]
No, it's public. But that's the git clone URL. The visiting URL is https://github.com/RobertoRoos/sawIntuitiveResearchKit/wiki.
However, since I've committed in two branches, you can't view those through the web.

(Yeah, this is all not really working out how I hoped it would)

**Comment by adeguet1** [comment]
We might want to have a quick zoom to iron out the processes if we decide to use forks/branches.  On my end, I cloned your repo (`sawIntuitiveResearchKitWiki`), checked out each branch of your repo and use a local diff tool (meld) on my Linux PC to manually merge with my clone of `sawIntuitiveResearchKit.wiki`.   And since I'm not that bright I also added some not so minor changes before committing (so now it's a real mess, see comment below).   At that point, considering GitHub is not making it easy to use their own tools on the wiki repository, I'm inclined to let user edit the wiki directly and I can just use simple history link available on github (e.g. https://github.com/jhu-dvrk/sawIntuitiveResearchKit/wiki/Calibration/_history).

One decision I just made is to remove the numbering in titles.  This way links to sections/subsections are less likely to be broken if a new section is added in the middle of a page.

One a side note, there is a small script in the wiki repository itself to generate the TOC (another feature I wish GH wiki would have).   The script usage is something like `./gh-md-toc.sh --insert Calibrations.md`.  The md file needs a couple of html tags first: `<!--ts-->` and `<!--te-->`

**Comment by RobertoRoos** [comment]
Thanks.

I agree the convenience of numbering is not worth the extra inconvenience.

Small reflection on our procedure: you don't have the exact commits I made, so my PR is sort of broken. Of course I can now just remove by branches.

I think an official fork might be good. You should be able to make a Github action to update another repo (e.g. the .wiki.git) automatically. Let me make an example, this sounds entertaining.

I'll close this issue as my stuff is in there now.

**Comment by RobertoRoos** [comment]
Got a working demo here with a fork and automatic updates: https://github.com/RobertoRoos/WikiTest

Merging a pull requests updates the real wiki.

Problem is this completely overrides the regular wiki edits. The official fork does a forced push, so any 'local' changes would get removed again. I don't think that would be acceptable.

Still, an official fork with manual updates could work.
